### ISSUE TITLE
Repo name should be gci-mentors-handbook

### ISSUE THREAD

**Issue by aliok** [JBossOutreach/mentors-handbook#3]
We don't use @JBossOutreach GH org only for GCI.

Let's do this later though; when GCI is over.

**Comment by HeroicHitesh** [comment]
@aliok Is this issue still relevant? If yes can you provide a bit more detailed description of what needs to be done?
If this issue is about renaming the repo from `mentors-handbook` to `gci-mentors-handbook` then, only a person with admin permissions can work on it.

**Comment by aliok** [comment]
GCI is no more. I will close this now
